[package]
name = "gtmpl"
version = "0.1.0"
authors = ["Florian Merz <flomerz@gmail.com>"]

[dependencies]
itertools = "0.6.0"
lazy_static = "0.2"
serde = "1.0.9"
serde_derive = "1.0.9"
serde_json = "1.0"
