[package]
name = "gtmpl"
version = "0.1.3"
authors = ["Florian Merz <flomerz@gmail.com>"]
description = "The Golang Templating Language for Rust"
license = "MIT"
repository = "https://github.com/fiji-flo/gtmpl-rust"
documentation = "https://docs.rs/crate/gtmpl"
keywords = ["golang", "template", "templating"]
categories = ["template-engine"]
readme = "README.md"
include = ["Cargo.toml", "src/**/*.rs", "tests/**/*.rs", "README.md", "LICENSE"]

[badges]
travis-ci = { repository = "fiji-flo/gtmpl-rust" }

[dependencies]
itertools = "0.6"
lazy_static = "0.2"
percent-encoding = "1.0.0"
gtmpl_value = { git = "https://github.com/fiji-flo/gtmpl_value.git" }
gtmpl_derive = { git = "https://github.com/fiji-flo/gtmpl_derive.git" }
#gtmpl_value = { path = "../gtmpl_value" }
#gtmpl_derive = { path = "../gtmpl_derive" }